### ISSUE TITLE
Search Feature Design

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#53]
I've been thinking about how to implement the search functionality and this is what I've come up with.

- Have a search bar, either drop down or static, at the top of each page
- Each search request can redirect to a servlet, such as `SearchServlet`
- Each search request should scan `User`, `Conversation`, and `Message` objects. 
- Currently, we already have a database of these 3 objects. For the messages, it might be a good idea to have a `Map<String, Set<Message>>`, where the key is a unique word and the set contains all the messages in which the word appears. This can also be done for all the other objects. 
- To handle these queries, we can start by only allowing single word requests. Then we can work on allowing multiple word requests that are separated by special characters. 

These are just my initial thoughts based on a similar project I did in one of my classes. Let me know what you guys think.

Fixes #62 , #64

**Comment by vocatwk** [comment]
So we would store all the messages in this map or store a copy of them? Also won't this end up to be really really big?

**Comment by vocatwk** [comment]
we also have think about what users will search for(first name, last name, full name, half of the first name ....) and the same with conversation title. So what would the keys be in the map?

**Comment by vocatwk** [comment]
I'm tempted to just iterate through users, conversations and messages and pattern match whatever the user enters but i'm guessing there is a more efficient way that will still allow for inexact searches and be efficent with time, but I can't seem to think of one.

**Comment by lealgamb** [comment]
Currently the way we store users and conversations, it is probably good enough to search through the lists we have based on username and conversation title. This can at least work for the MVP. For the messages, if we go through with the map, then this could be a possibility. 
- If it is a new word, add it to the map and create a set that stores the message.
- If the word is already in the map, then just add the message to the set.

**Comment by lealgamb** [comment]
For the inexact searches, I'm not sure if this would work with the search bar (although it seems like it will), but we can try to use Dialogflow. I was looking at this video and it seems like this can help us with pattern matching/inexact searches. https://www.youtube.com/watch?v=5r4AAIfe4Rw

**Comment by vocatwk** [comment]
You mean create to create the map? My concern with that we'd be storing copies of messages in each word that it happens to contain which doesn't seem worth it to me.

**Comment by lealgamb** [comment]
Yeah I see your point. So then if we just iterate through the messages searching for a word, would we check each message and see if it contains the word?

**Comment by vocatwk** [comment]
And I haven't seen the full video yet(I will later on) but it seems to me that that has more to do with figuring out what a user is asking a chat bot so it knows how to respond.

**Comment by vocatwk** [comment]
and yes we would check for the word or phrase in the message but this is also very brute force and very inefficient.

**Comment by lealgamb** [comment]
Yeah I'm not too sure about the chat bot idea. It might be possible to get its response on the back-end side so we know what the user is searching for but I'm not sure. And yeah haha, but the map has a lot of overhead like you said.

**Comment by vocatwk** [comment]
Not sure if this is any better but we could have the map be Map<String, Set<MessageId>> and then map from messageId to message. I figure it would be better to have duplicates or message id's than message objects. but that still won't fix the inexact searches problem.

**Comment by lealgamb** [comment]
I see what you mean. So first get the messageId based on a keyword, then get the message from the messageId? This would still need a set of messageId's, right?

**Comment by vocatwk** [comment]
yeah exactly.

**Comment by yebrahim** [comment]
Late to the party, here are my two cents:
- What you're thinking about building is called an [inverted index](https://en.wikipedia.org/wiki/Inverted_index). It's a fairly common problem in databases and search indexes, and there are some efficient ways of implementing one (think Google scale).
- However, we shouldn't be thinking about this from the get go. Just build a simple version that is slow but functional, then we can look for ways to speed it up. As they say, "pre optimization is the root of all evil."
- That said, here are some ideas, you're free to adapt or criticize as you want. :)
  - Don't build the index, loop over conversations in runtime. You can do some back of the envelop calculations to show this index can grow really large, and it's probably in the realm of distributed computing.
  - Loop only to find the first 10 or so results, return them and display a "Show More" button, then loop in the background for the next 10 and stop. Every time the user clicks the button, show the next cached 10 results and loop for 10 more.
  - Build the index, but only up to a certain size, swap out old conversation words as you get new ones. [Search engines don't index the entire web anyway](https://googleblog.blogspot.com/2008/07/we-knew-web-was-big.html). :)
  - The index can be a simple map of ([non-stop](https://www.ranks.nl/stopwords)) word -> conversation id.
  - Start by building just searching for users and names of conversations. Even this can be a large amount of data, but its implementation should be more straightforward.
- Your search servlet doesn't have to also serve the HTML. You can have some Javascript call the servlet as the user is typing, so that they see the results update on the same page, below the search bar.

If you decide to proceed with search, think about these points, and let's set a multi-part plan, the MVP of which should not be too complicated algorithmically, but should be a functional search feature, however you want it to look like. :)

**Comment by vocatwk** [comment]
if the map is from word to conversation id, does that mean then the messages in that conversation then have to be searched. Sort of like narrowing the search down?

**Comment by yebrahim** [comment]
You're right. It should be word -> message-id.
The `Message` model contains the id of the parent conversation, so this is all the info we need.

**Comment by lealgamb** [comment]
Thanks for these ideas. I like the point about limiting the search to 10 results at a time. Also, I'm a little confused about making an index of non-stop words. Is it to only search for the key words?

**Comment by lealgamb** [comment]
I was wondering if a splay tree would be a good way to store the database? It still has the memory problem, but it might be good since it the most frequent searches will be splayed to the root.

**Comment by yebrahim** [comment]
I'm not sure this is a requirement that we want to build the feature around. Seems to me like this would be a nice data structure to build something like a memory cache out of, but I'm not sure if it's well suited for a random search kind of problem.

Also, one note about the implementation is paying attention to the cost of complexity. Complex implementations can be very taxing in a team environment. :) I'd rather start with something simple and then solving more advanced problems as they pop up.

**Comment by lealgamb** [comment]
Thanks for the feedback. 😃

**Comment by lealgamb** [comment]
Just wondering it it's okay to close this issue now and make a new one for the drop down feature?

**Comment by yebrahim** [comment]
It's your Github issue, feel free to manage it however you like. For book keeping purposes though, I'd add a reference here to the search PR, and create a new issue to complete the dynamic dropdown work, and reference it here too.
