### ISSUE TITLE
Search Bar Instant Search - Using Fetch Request

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#62]
I've been working on the steps @yebrahim provided and this is what I have so far. 

In `SearchServlet` I added the following in `doGet()`:

```
String json = new Gson().toJson(users);
response.setContentType("application/json");
response.setCharacterEncoding("UTF-8");
response.getWriter().write(json);
```

This successfully created a JSON object, but it prints it on the page:
![image](https://user-images.githubusercontent.com/31300741/41636523-e3751a8a-7403-11e8-8445-fef4e85e58a4.png)

My questions are:

1. How do I only make the JSON object have the following:
```
[{
  "name": "user1",
}, {
  "name": "user2"
}]
```

2. I understand how to call a function using keypress, but how do I call the `[fetch]` function?

**Comment by yebrahim** [comment]
Nice!

1. You don't really need to, you're already sending the name, along with other info. Unless you want to restrict the data you're sending for any other concerns (security perhaps), this is fine. If you do want to control what you send, build the JSON object yourself. [This page](https://www.tutorialspoint.com/json/json_java_example.htm) includes a simple example, and I also think the Gson library looks a little more complicated than is needed here.

2. `fetch` is a built-in function in all modern browsers (see [browser compatibility here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility)), so you can just call it in the Javascript code. Something like:
```
...onkeypress="keypressed"...
...
function keypressed() {
  fetch('/search?q=' + document.querySelector('#searchbox').value)
    .then(result => doSomethingWithResults(result));
}
```
Does this help?

**Comment by lealgamb** [comment]
Yes! If we fetch `'/search?q=' + document.querySelector('#searchbox').value` then does this only work from the search results page?

**Comment by yebrahim** [comment]
The page where you’re running this JavaScript code must also contain the search box, since it’ll use its contents in the query. If your search box and this code are in the header, you’ll have them running on all pages.

**Comment by lealgamb** [comment]
I'm not sure why I'm getting this error. After Googling I found some answers saying the response might be HTML, but I set the type to `"application/json"`.

![image](https://user-images.githubusercontent.com/31300741/41749598-3a739d2a-756c-11e8-8431-6eafb5d3f794.png)
![image](https://user-images.githubusercontent.com/31300741/41749606-50165988-756c-11e8-8c3a-acfce1d72f3c.png)

**Comment by lealgamb** [comment]
I printed the response type and it's coming out as basic.

**Comment by yebrahim** [comment]
The "unexpected token < in JSON" error means the JSON is malformed. Can you paste the JSON you're sending here?
Also, if you push your branch (no need for a PR just yet), you can reference actual code lines here so I can look at the code to be able to help better.

**Comment by yebrahim** [comment]
Sorry for the late response, travels!

I couldn't identify the error just by looking through the code, so here's what I did:
- I checked out and built your branch on my machine (btw, I'm getting a NullPointerException, I think you might need to rebase: `git rebase origin/master`, or start fresh from master).
- After going around the NPE above, I logged in and tried typing into the search box, with the dev tools window open on the network tab to see the requests, this is what I saw:
![image](https://user-images.githubusercontent.com/1424661/41819319-5946ddd0-7773-11e8-9933-a0d57c0fd2c9.png)

Look at the content of the Response tab. You can see we're not actually getting through to the search servlet at all (you can confirm this by adding a print statement in the servlet, it shouldn't fire). My immediate suspicion was that we're getting instead to the login filter, which is blocking the request. I added another print statement with the username in there, and indeed, it got a `null`.
- If we now switch to see how the search request is made in the dev tools, by looking at its Headers tab, you'll see it does not contain the session cookie. Contrast this by looking at any other request that is made by the browser, such as the `http://localhost:8080/conversations` request, it should contain the cookie. [Read this](https://medium.com/@kasunpdh/session-management-in-java-using-servlet-filters-and-cookies-7c536b40448f) for more on session cookies, it's a topic that can get overwhelming pretty easily, so I'd just try to get a general idea about it, no need for too much detail.
- This is because the browser sends the session cookie with each request by default, but when you do it using the `fetch` function, you'll need to tell it you want to include the session cookie in the request. See this official `fetch` guide for how to do it: https://github.com/github/fetch#sending-cookies.
- If we now include credentials, we get something promising:
![image](https://user-images.githubusercontent.com/1424661/41819448-9dcee536-7775-11e8-801d-ae968ccd72cf.png)

Note, however, that you should only be sending the JSON data, not the HTML page content along with it. This was fine for the static results page, where you also want to render the HTML, but for the data API call, you just want the data.

Hope this helps?

**Comment by lealgamb** [comment]
Thanks for letting me know about the NPE. And also thanks for showing me the network tab, I had no idea about it.

I'll make sure to include the cookie from now on. In terms of only sending the JSON data, is it possible to make a .json file and fetch that file instead?

**Comment by yebrahim** [comment]
Well you're getting your data by querying the datastore, so writing it to a file, serving that file, then deleting it is a lot more work than necessary, plus, you'll still need to turn your data into JSON format anyway, so I don't see why you'd want to do that.
You can easily just build a JSON string out of your data (you're already doing that), then just send it, without sending the HTML file. (i.e. just delete [this line](https://github.com/vocatwk/CodeU-Nemo/blob/78b4ed314d12f0b06cb21deb014e2654bcb10c95/src/main/java/codeu/controller/SearchServlet.java#L88))

**Comment by lealgamb** [comment]
By deleting that line then will the results page not work?

**Comment by yebrahim** [comment]
I didn't realize you wanted both the dynamic search and the static results page. If that's the case, best thing is to create two different endpoints, maybe `/search` and `/searchPage`.

**Comment by lealgamb** [comment]
I'm fine with either or. I'll work on the instant search feature and then work on `/searchPage` if you guys think it's worth it.

**Comment by yebrahim** [comment]
I personally think the dynamic search dropdown is enough. I like that it also doubles as a widget to add people to a conversation, in case we might decide we want that.

**Comment by lealgamb** [comment]
Sounds good. So now the next step is to iterate through the results and make a div out of each user, right?

**Comment by yebrahim** [comment]
Yes. I'd look into jQuery to see if it makes the syntax easier, I recall @jasminechau2 also wanted to use it for something else?

**Comment by jasminechau2** [comment]
Here is a link: http://www.encodedna.com/jquery/create-a-facebook-like-notifications-using-jquery-css.htm

@lealgamb  this is a resource I was looking at

**Comment by lealgamb** [comment]
Thanks for the link @jasminechau2 

I kind of already have something but I can change it if needed. I'll make a PR for review.
