### ISSUE TITLE
Problem Getting Messages in ChatServlet

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#81]
https://github.com/vocatwk/CodeU-Nemo/blob/6ec5b009616f51b256da42a38c903a876e4c2fae/src/main/java/codeu/controller/ChatServlet.java#L147-L148

I ran into a problem with the two lines above. Line 147 works as long as the conversation is being made private/public. However, when a message is being sent, `messageContent` becomes `null` and `purpose` becomes the actual message.
 
Here are some debugging statements:
![image](https://user-images.githubusercontent.com/31300741/42304682-70d35688-7fdc-11e8-824f-b80f7f681315.png)

**Comment by yebrahim** [comment]
cc @vocatwk.

Thanks for catching/reporting this.
It looks like we're using the same POST endpoint (/chat/chat_id) for two purposes: sending a new message to the chat, and modifying the chat's metadata (private/public state). We need to differentiate between these two operations somehow.

Personally I'd recommend following the standard way [different HTTP methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) are meant for. In this case, a POST would be used to create a new resource in the conversation (a new message), and a PUT or PATCH would be used for modifying the existing conversation resource, such is the case when changing status to public or private.

Although this is recommended, it can still be implemented in various different ways, such as using a header, a query parameter, or a hint in the request body to decide what the request wants.

**Comment by vocatwk** [comment]
Oops sorry about that, I should have double checked to make sure it works. I wanted to differentiate the two POST requests, that's why I was using a header at first before I changed back to the body but I didn't know about PUT or PATCH. Those do sound like better option, I'll fix that with the PR I'm about to send out right now.

**Comment by yebrahim** [comment]
Is that something we can add a test for?

**Comment by vocatwk** [comment]
I added a test condition in ChatServletTest, testDoPost_messageNull(). is that what you had in mind?

**Comment by yebrahim** [comment]
Yes, I think this is enough for a unit test.
A better test for this is what's called an integration test, which tests the functionality of both pieces: the frontend (JSP) code, against the backend (servlet) code. We don't have infrastructure in place to support this though, and I don't think we have the bandwidth to take on something like that, so that's fine.
