### ISSUE TITLE
Add the ability to remove users from conversations

### ISSUE THREAD

**Issue by vocatwk** [vocatwk/CodeU-Nemo#98]
Hey guys, just wanted to discuss the design for this. Should I add a new modal for this or do it in the same modal as add users?

**Comment by yebrahim** [comment]
The UI design that the user interacts with shouldn't have too much say in the underlying implementation in this case. You can still keep the `addMembers` methods and choose to use them to update the conversation, that's up to you.
But yes, in this case it probably makes sense to have a `setMembers` method where you just pass in the modified set of members.

**Comment by vocatwk** [comment]
So I wanted the 'Save Changes'(used to be 'Add users') button to be enabled only when the user has made changes to the list of members in the conversation. I could compare the list to the last saved list every time the user adds/remove users or I could enable it once the user either adds/remove a user for the first time and then keep it enabled even if the users reverses the adds/removes they made. The latter would mean sometimes sending the POST request and setting members even though the list hasn't changed. Is there any better way to do this?

I was also thinking about of setting it back to the last saved list when the modal closes but since there are 3 ways of closing the modal I'm not sure how to implement that instead maybe a 'discard changes' button?

**Comment by yebrahim** [comment]
I would make an API call to fetch the latest set of users in the conversation every time the modal opens, and keep comparing against it every time the user makes a change in the queued set of users.
This is also good to refresh the users in case they have changed since the last time the user opened the page.
There's no good way to avoid the constant comparisons, but they're very cheap too, so I wouldn't worry too much about it.

**Comment by lealgamb** [comment]
I agree with making a fetch request each time, specially because it lets us refresh the users.
